# This is a python driver for FiberGrid optical sensor framework
import cv2 # you have to have OpenCV installed for this to work


def regionBrightness(img, x, y, half):
    region = img[ x-half:x+half, y-half:y+half ]
    m = cv2.sumElems(region)
#    print ("(x,y,h,m %d,%d,%d) " % (x,y,half), m, end="\n", flush=True )
    return int( m[0] + m[1] + m[2] )


# these constants are generated by FiberGrid calibration utility
# it creates fiberinit.h file as a result of calibration of you fibergrid device
CAM_ID = 0                                   # from fiberinit.h
MIN_DISTANCE = 8                             # from fiberinit.h
FIBERS = [ [20,20],[20,200],[200,20],[200,200] ] # from fiberinit.h

sensors = [0]*len(FIBERS) # make it same size as FIBERS[]
HALF = int(MIN_DISTANCE/2)

cam = cv2.VideoCapture(CAM_ID)
if False == cam.isOpened():
    print("Can not open camera.")
    exit()

ret, img = cam.read()
while ret:
    for i in range(len(FIBERS)): # each fiber is defined by x,y coordinates
        x,y = FIBERS[i]
        sensors[i] = regionBrightness(img, x, y, HALF)
    print (sensors)
    ret, img = cam.read(img)
