#ifndef INCLUDED_FIBERINIT_H
#define INCLUDED_FIBERINIT_H
// This file is auto generated by fibergrid calibration utility on 2019-07-07 19:56:14
#include <vector>
#define FIBERGRID_DEBUG "Comment this line to disable driver's debug video window."
namespace fibergrid {
    const int CAM_ID = 1;
    const int MIN_DISTANCE = 12;
    const int FIBER_COUNT = 7;
    const std::vector<int> FIBERS = {
        351, 127,
        335, 134,
        349, 145,
        331, 154,
        312, 164,
        329, 174,
        308, 183
    }; // FIBERS
} // namespace fibergrid
#endif