#ifndef INCLUDED_FIBERINIT_H
#define INCLUDED_FIBERINIT_H
// This file is auto generated by fibergrid calibration utility on 2019-04-28 22:00:27
#include <vector>
#define FIBERGRID_DEBUG "Comment this line to disable driver's debug video window."
namespace fibergrid {
    const int CAM_ID = 1;
    const int MIN_DISTANCE = 12;
    const int FIBER_COUNT = 7;
    const std::vector<int> FIBERS = {
        347, 168,
        365, 177,
        331, 179,
        349, 187,
        367, 197,
        335, 200,
        351, 207
    }; // FIBERS
} // namespace fibergrid
#endif